---
- name: Copy node_exporter config file
  ansible.builtin.template:
    src: node_exporter.default.conf.j2
    dest: "{{ node_exporter_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: Create textfile collector directory
  ansible.builtin.file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 0775

- name: Install node_exporter systemd service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: Enable node_exporter systemd service
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
