groups:
- name: Node alert rules
  rules:
  # Alert for any instance that has average CPU idle < 20%
  - alert: NodeHighCpuUsage
    expr: avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[1m]) * 100) < 20
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "{{ $labels.instance }} has a average CPU idle (current value: {{ $value }}s)"
