groups:
- name: Postgres alert rules
  rules:
  # Alert for high of slow queries
  - alert: PostgresSlowQueries
    expr: avg by (datname) (rate(pg_stat_activity_max_tx_duration{datname!~"template.*"}[2m])) > 2 * 60
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "PostgreSQL high number of slow for database {{ $labels.datname }}"
      description: "PostgreSQL high number of slow queries for database {{ $labels.datname }} with a value of {{ $value }}"
