---
node_exporter_version: "1.6.1"

node_exporter_user: node-exporter
node_exporter_group: "{{ node_exporter_user }}"

node_exporter_bin: /usr/local/bin/node_exporter
node_exporter_config_file: /etc/default/node_exporter
node_exporter_textfile_dir: /var/lib/node_exporter

node_exporter_web_listen_address: "0.0.0.0:9100"
node_exporter_web_telemetry_path: "/metrics"

node_exporter_options:
  - collector.systemd
  - collector.processes
