---
- name: Configure prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
    validate: "{{ prometheus_bin_dir }}/promtool check config %s"
  notify:
    - reload prometheus

- name: Default alerting rules file
  ansible.builtin.template:
    src: alert.rules.j2
    dest: "{{ prometheus_config_dir }}/rules/default.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
    validate: "{{ prometheus_bin_dir }}/promtool check rules %s"
  when:
    - prometheus_alert_rules != []
  notify:
    - reload prometheus

- name: Template alerting rule files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/rules/"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
    variable_start_string: "[["
    variable_end_string: "]]"
    validate: "{{ prometheus_bin_dir }}/promtool check rules %s"
  with_fileglob:
    - "{{ inventory_dir }}/templates/prometheus/rules/*.yml"
  notify:
    - reload prometheus

- name: Install prometheus systemd service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus

- name: Enable prometheus systemd service
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    enabled: true
    state: started
