---
prometheus_version: "2.47.2"

prometheus_user: prometheus
prometheus_group: "{{ prometheus_user }}"

prometheus_bin_dir: /usr/local/bin
prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /var/lib/prometheus
prometheus_force_install: false

prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_web_external_url: ""

prometheus_args: {}
#  storage:
#    tsdb.retention.time: 30d
#    tsdb.retention.size: 0
#  alertmanager.timeout: 10s
#  web.enable-admin-api:
#  enable-feature:
#    - promql-at-modifier
#    - remote-write-receiver

prometheus_config:
  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
  alerting:
    targets:
      group_name: prometheus
      port: 9093
  scrape_configs:
    - job_name: "prometheus"
      static_configs:
        - targets: "{{ groups['prometheus']|map('regex_replace', '^(.*)$','\\1:9090')|list }}"
    - job_name: "node-exporter"
      static_configs:
        - targets: "{{ groups['prometheus']|map('regex_replace', '^(.*)$','\\1:9100')|list }}"

# yamllint disable rule:line-length
prometheus_alert_rules:  # noqa yaml[line-length]  # noqa line-length
  - alert: PrometheusTargetMissing
    expr: up == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: '{% raw %}Prometheus target missing (instance {{ $labels.instance }}){% endraw %}'
      description: '{% raw %}A Prometheus target has disappeared. An exporter might be crashed. VALUE = {{ $value }}  LABELS: {{ $labels }}{% endraw %}'
# yamllint enable rule:line-length
